[Refactor] API 호출 interface 추가 작업
woowa-techcamp-2022/web-fleamarket-9 pull request #294
Opened 2022-09-18 10:40 UTC by padosum

## Description

즐거운 주말입니다.
#267 에 남기신 내용대로 인터페이스를 추가해봤습니다.
- 우선 동네설정, 로그인, 회원가입에 적용해봤는데 리뷰 후 다른 파일에 적용하면 좋을 것 같습니다. 
- pr을 보내려하니 추가하신 e2e 테스트에 오류가 나는데 확인해보겠습니다.

## Related Issues

resolve #267 

## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] Issue TODO finished
- [ ] No Conflicts with the base branch

## Elapsed time
1h

2022-09-18 12:33 UTC, kokocan12 commented
헉 api호출하는 부분 제가 수정하고 있었는데 아직 반영이 안되어 있거든요

2022-09-18 12:37 UTC, kokocan12 commented
테스트도 폴더 구조가 조금 바뀌었는데 아직 마무리가 안되어서 pr전인데 충돌이 두렵네요 ㄷㄷ

2022-09-18 14:05 UTC, padosum commented
고럼 작업 마무리되실 때까지 기다리겠습니다~

2022-09-19 10:46 UTC, kokocan12 requested changes
제가 작업한 것들은 dev브런치에 머지하였습니다. 그래서 연정님이 작업하신 부분과 컨플릭트가 나는데 이 부분은 변경이 필요할 것 같습니다.

제가 확인해서 변경을 하긴했는데 한번 더 확인해주세요~!

2022-09-19 11:42 UTC, kokocan12 commented
컨플릭트 나는 부분은 제가 수정하였습니다.

2022-09-19 11:46 UTC, kokocan12 commented on client/src/utils/api.ts
> +export default Api;
API 유틸을 추가하셨네요!
다만 저도 같은 유틸을 추가했는데 dev브런치 src/remotes 디렉토리에 해당 유틸을 구현하여서,
통일이 필요할 것 같습니다.

2022-09-20 03:03 UTC, padosum commented on client/src/utils/api.ts
> +export default Api;
작업하신거랑 적절히 섞어서...
```js
  get: function get<Response = unknown>(url: string) {
    return axios.get<Response>(url).then((res) => res.data);
  },
 // ⬇️
  get: async <Response>(url: string): Promise<Response> => {
    const { data } = await request({ url });
    return data;
  },


// request
const request = async (option: AxiosRequestConfig) => {
  const {
    method = 'GET',
    url,
    params,
    headers = { 'Content-Type': 'application/json' },
    data,
  } = option;

  const config = {
    url,
    method,
    params,
    headers,
    data,
  };

  return axios(config);
};
```
요렇게 바꾸는 것은 어떨까요? 
`request`로 한번 더 감싸주면 저희 프로젝트에서는 상관없지만 `fetch`를 사용할 경우에도 재사용할 수 있을 것 같습니다.

2022-09-20 05:40 UTC, kokocan12 commented on client/src/utils/api.ts
> +export default Api;
request로 감싸는 것은 좋은 생각이네요!
다만 조금 개선이 필요할 것 같은데,
request함수에 제네릭을 추가해서 반환되는 데이터 타입힌팅이 가능하도록 변경해주실 수 있을까요?

2022-09-27 03:24 UTC, kokocan12 approved these changes
기존 http모듈 삭제하고, 작성해주신 api 모듈로 변경완료했습니다~

2022-09-27 03:24 UTC, merged